<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Argo.Domain\**\*.cs" />
    <Compile Remove="Models\**" />
    <Content Remove="Argo.Domain\**" />
    <Content Remove="Models\**" />
    <None Remove="Argo.Domain\**" />
    <None Remove="Models\**" />
    <EmbeddedResource Remove="Argo.Domain\**" />
    <EmbeddedResource Remove="Models\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Argo.Domain\Argo.Domain.csproj" />
    <ProjectReference Include="..\Argo.Application\Argo.Application.csproj" />
    <ProjectReference Include="..\Argo.Infrastructure\Argo.Infrastructure.csproj" />
    <ProjectReference Include="..\Argo.Persistence\Argo.Persistence.csproj" />
  </ItemGroup>

</Project>
