<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="FluentEmail.Core" />
	<PackageReference Include="FluentEmail.Smtp" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Argo.Application\Argo.Application.csproj" />
  </ItemGroup>

</Project>
